#MAINTAINER yanlinw

jobserver:
   build: ./spark-jobserver-docker
   links:
    - hadoop
   hostname: jobserver
   volumes:
    - ~:/opt/mount/host:rw
   ports:
    - "18090:8090"
    - "9999:9999"
    - "2929:2929"
   expose:
    - "2929"
    - "32456"
    - "32457"
    - "32458"
    - "32459"
    - "32460"
    - "32461"
    - "32462"
    - "32463"
    - "32464"
    - "32465"
    - "32466"
    - "32467"
    - "32468"
    - "32469"
    - "32470"
    - "32471"
    - "32472"

hadoop:
   build: ./hadoop-docker
   hostname: hadoop
   volumes:
    - ~:/opt/mount/host:rw
   ports:
    - "9000:9000"
    - "50010:50010"
    - "50020:50020"
    - "50070:50070"
    - "50075:50075"
    - "50090:50090"
    - "19888:19888"
    - "8030:8030"
    - "8031:8031"
    - "8032:8032"
    - "8033:8033"
    - "8040:8040"
    - "8042:8042"
    - "8088:8088"
    - "49707:49707"
    - "2122:2122"
